### PR TITLE
fix: #1225 ui for mobile client side app

### LINKED ISSUE #1225: UI for mobile client-side app
**Summary:** As the apps in the developer and client portal are now standalone and accessible via another page rather than a modal, we should support both options in a mobile view 

**Relates to ticket:** https://github.com/reapit/foundations/issues/1125
**Client side**: https://github.com/reapit/foundations/issues/1206
**Developer side**: https://github.com/reapit/foundations/issues/1210

### General
- Headers: H5, Museo Sans 700
- Colour: #12263f
- Text: Roboto, 14px 
- Colour: 556986
- Guttering: 1rem (as with submit app and other pages in the developer portal)

In mobile view we should only display the main page (not the left hand navigation) and move the contents which would have been in the left-hand navigation to the bottom of the app detail

### Main Page
- Icon image to the left of App Name
- App Name: H2, Museo Sans 300
- Directly underneath, add ‘Verified by Reapit’ and a green tick (the same green tick when an app is listed) 
- To the right, add the ‘Install’ or ‘Uninstall’ button 
- Summary: App ‘Summary’
- Image: ScreenShot 2 
- Description: App ‘Description’
- Permissions: H5 heading – List app permissions/scopes
- Images: Display remaining screenshots (2,3,4,5) stacked (image lightbox TBC) 
- Should display ‘Category’ if one has been selected, use Lozenge/tag component  
- Should display ‘Desktop Integration Types’ if applicable (as above)
- Heading: Developer (Logo upload TBC)
- Heading: About Developer (text TBC)
- Heading: Contact Developer 
- Button: Need Help? 
Action: Should open a modal with the ‘Support’ and ‘Telephone’ fields of the app (UI TBC)

See mockup: 
AppPage---Mobile

### PR DESCRIPTION
**Pull request by phmngocnghia**
fixes #1225

### CODE REVIEW

File: packages/marketplace/src/components/pages/client-app-detail/app-content.tsx [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+const AppContent: React.FC<AppContentProps> = ({ appDetailData, desktopIntegrationTypes = [] }) => {
+  const { summary = '', description = '', category, scopes = [], media = [] } = appDetailData
+  /**
+   * 0 = icon
+   * 1 = featured media
+   * 2 -> nth: extra media
+   */
+  const extraMedia = media.filter((_, index) => index > 1)
+  console.log({
```
Comment (tanphamhaiduong) [inline packages/marketplace/src/components/pages/client-app-detail/app-content.tsx:86]: Pls remove console

File: packages/marketplace/src/components/pages/client-app-detail/app-content.tsx [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+      {scopes.map(scope => (
+        <li key={scope?.description}>{scope?.description}</li>
+      ))}
+    </ul>
+  </div>
+)
+
+export const renderCategory = (category: CategoryModel | undefined) => {
+  if (!category) {
+    return undefined
```
Comment (tanphamhaiduong) [inline packages/marketplace/src/components/pages/client-app-detail/app-content.tsx:38]: I think null is better than undefined

File: packages/marketplace/src/sagas/apps/apps.ts [hunk 3]
```diff
@@ -8,13 +11,26 @@ import { logger } from 'logger'
 import { fetchAppApiKey, fetchAppDetail, FetchAppDetailParams } from '@/services/apps'
 import { developerFetchAppDetailSuccess } from '@/actions/developer'
 
+export const fetchDesktopIntegrationTypes = async () => {
```
Comment (tanphamhaiduong) [inline packages/marketplace/src/sagas/apps/apps.ts:14]: Pls move this function to services folder

File: packages/marketplace/src/reducers/client/app-detail.ts [hunk 4]
```diff
@@ -3,7 +3,11 @@ import { Action } from '@/types/core'
 import { clientFetchAppDetail, clientFetchAppDetailSuccess, clientFetchAppDetailFailed } from '@/actions/client'
 import { isType } from '@/utils/actions'
 
-export type AppDetailData = (AppDetailModel & { apiKey?: string }) | null
+export type AppDetailDataNotNull = AppDetailModel & {
+  apiKey?: string
+}
+
+export type AppDetailData = AppDetailDataNotNull | null
```
Comment (tanphamhaiduong) [inline packages/marketplace/src/reducers/client/app-detail.ts:10]:
```
AppDetailData = AppDetailModel & {
  apiKey?: string
} | null
```

Comment (phmngocnghia) [reply packages/marketplace/src/reducers/client/app-detail.ts:10]: I intentionally use `AppDetailDataNotNull` because I need 
`
AppDetailModel & {
  apiKey?: string
} 
`

without null stuff since the selector won't return `null`
