### PR TITLE
fix: #902 Issue with text on after registering as a Developer

### LINKED ISSUE #902: Issue with text on after registering as a Developer
**Describe the bug**
Slight issue with the text, should read 'Check your email' not 'Check you email' when registrting as a developer. Please also apply slight spacing between the text and 'Login' button. 

image

### PR DESCRIPTION
**Pull request by phmngocnghia**
fix #902

### CODE REVIEW

File: packages/marketplace/src/components/pages/register.tsx [hunk 1]
```diff
@@ -135,7 +135,7 @@ export const Register: React.FunctionComponent<RegisterProps & FormikProps<Regis
             }
             isCenter
           >
-            Check you email to confirm your account
+            <div className="mb-3">Check you email to confirm your account</div>
```
Comment (willmcvay) [inline packages/marketplace/src/components/pages/register.tsx:138]: Should be "your email" not "you email", sorry!

Comment (phmngocnghia) [reply packages/marketplace/src/components/pages/register.tsx]: typo updated 👍
